/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat1;

import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 50684
 */
public class GuestGUI extends javax.swing.JFrame {
    //al usar private finals se hace que no se pueda aplicar del todo herencia sobre las variables
    private final DefaultTableModel modelo;
    private final Client cliente;
    private final Server servidor;
    private String mensaje[];//el array es porque el mensaje viene en una lista que splitteo con el °

    /**
     * Creates new form GuestGUI
     */
    //se inicializa la gui y se crean el client y el sv
    public GuestGUI() {
        initComponents();
        modelo = (DefaultTableModel) tabla1.getModel();
        servidor = new Server(modelo, Integer.parseInt(puerto_Field.getText()));//agarra el puerto y lo convierte en integer(parseint)
        cliente = new Client(IP_Field.getText(), Integer.parseInt(puerto_Field.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        mensaje_field = new javax.swing.JTextField();
        IP_Field = new javax.swing.JTextField();
        puerto_Field = new javax.swing.JTextField();
        nombre_field = new javax.swing.JTextField();
        label_name = new java.awt.Label();
        label_port = new java.awt.Label();
        label_ip = new java.awt.Label();
        cuadro_de_texto = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setActionCommand("send");
        button1.setBackground(new java.awt.Color(0, 204, 204));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 12)); // NOI18N
        button1.setLabel("Ok!");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        mensaje_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensaje_fieldActionPerformed(evt);
            }
        });
        mensaje_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mensaje_fieldKeyPressed(evt);
            }
        });

        IP_Field.setText("127.0.0.1");

        puerto_Field.setText("9000");
        puerto_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puerto_FieldActionPerformed(evt);
            }
        });

        nombre_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_fieldActionPerformed(evt);
            }
        });

        label_name.setBackground(new java.awt.Color(255, 255, 255));
        label_name.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        label_name.setText("Nombre");

        label_port.setBackground(new java.awt.Color(255, 255, 255));
        label_port.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        label_port.setText("Puerto");

        label_ip.setBackground(new java.awt.Color(255, 255, 255));
        label_ip.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        label_ip.setText("IP");

        tabla1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Mensaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla1.getTableHeader().setReorderingAllowed(false);
        cuadro_de_texto.setViewportView(tabla1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensaje_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_port, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IP_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puerto_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cuadro_de_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puerto_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IP_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuadro_de_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mensaje_field)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try {
            servidor.Update(Integer.parseInt(puerto_Field.getText()));
            cliente.Update_Data(IP_Field.getText(), Integer.parseInt(puerto_Field.getText()));
            cliente.enviar_mensaje(nombre_field.getText(),mensaje_field.getText());
            modelo.addRow(new Object[]{nombre_field.getText(),mensaje_field.getText()});
            mensaje_field.setText(null);
        } catch (IOException ex) {
            System.out.println("no se llamó la función");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void mensaje_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensaje_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensaje_fieldActionPerformed

    private void mensaje_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mensaje_fieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                servidor.Update(Integer.parseInt(puerto_Field.getText()));
                cliente.Update_Data(IP_Field.getText(), Integer.parseInt(puerto_Field.getText()));
                cliente.enviar_mensaje(nombre_field.getText(),mensaje_field.getText());
                modelo.addRow(new Object[]{nombre_field.getText(),mensaje_field.getText()});
                mensaje_field.setText(null);
            } catch (IOException ex) {
                System.out.println("no se llamó la función");
            }
        }
    }//GEN-LAST:event_mensaje_fieldKeyPressed

    private void puerto_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puerto_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puerto_FieldActionPerformed

    private void nombre_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IP_Field;
    private java.awt.Button button1;
    private javax.swing.JScrollPane cuadro_de_texto;
    private java.awt.Label label_ip;
    private java.awt.Label label_name;
    private java.awt.Label label_port;
    private javax.swing.JTextField mensaje_field;
    private javax.swing.JTextField nombre_field;
    private javax.swing.JTextField puerto_Field;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
